name: Build docker

on:
  push:
    branches:
      - main

jobs:
  update-meta:
    runs-on: self-hosted

    steps:
      # Check out the repository code
      - uses: actions/checkout@v4

      - name: Build 
        run: |
          npm install
          npm run build
          mv /app/dist /root/tucik/landing