name: Build docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Check out the repository code
      - uses: actions/checkout@v4

      - name: Build 
        run: |
          npm install
          npm run build
          mv dist /root/tucik/landing
      - name: Refresh
        run: |
          systemctl restart landing